import spacy
from spacy import displacy
from spacy.matcher import Matcher

nlp = spacy.load("en_core_web_sm")
matcher = Matcher(nlp.vocab)
pattern1 = [{"POS": "NOUN"}, {"POS":"NOUN"}]
pattern2 = [{"POS": "NOUN"}, {"POS": "ADJ"}]
pattern3 = [{'POS': 'NOUN'},
           {'POS': 'ADJ', 'OP': '?'},
           {'POS': 'ADP'},
           {'POS': 'NOUN'},
           {'POS': 'ADJ', 'OP': '*'}]
pattern4 = [{'POS': 'NOUN'},
           {'POS': 'ADJ', 'OP': '?'},
           {'POS': 'ADP'},
           {'POS': 'NOUN'},
           {'POS': 'ADJ', 'OP': '*'}]
pattern5 = [{'POS': 'NOUN'},
           {'POS': 'ADJ', 'OP': '?'},
           {'POS': 'ADP'},
           {'POS': 'VERB'},
           {'POS': 'NOUN', 'OP': {'POS': 'ADJ', 'OP': '*'}}]

matcher.add("Concept1", None, pattern1)
matcher.add("Concept2", None, pattern2)
matcher.add("Concept3", None, pattern3)
matcher.add("Concept4", None, pattern4)
matcher.add("Concept5", None, pattern5)

doc = nlp("A match is a tool for starting a fire. Typically, modern matches are made of small wooden sticks or stiff paper. One end is coated with a material that can be ignited by frictional heat generated by striking the match against a suitable surface. Wooden matches are packaged in matchboxes, and paper matches are partially cut into rows and stapled into matchbooks.")

print([t.text for t in doc])
matches = matcher(doc)
for match_id, start, end in matches:
    span = doc[start:end]
    print(span.text)
